version: '3.8'

services:
  frontend:
    image: my-frontend-image
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:80"  
    depends_on:
      - back-end

  back-end:
    image: my-backend-image
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

  proxy:
    image: my-proxy-image
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - back-end
  